/* Monthly Money Plan: November 2026 financial plan starts after vacation. Vacation: Sep 17-Oct 31, 2026. */
(function(){
  const PLAN_KEY='moneyPlan';
  const START_MONTH='2026-11';
  const VACATION_START='2026-09-17';
  const VACATION_END='2026-10-31';
  const defaultPlan={cardPct:50,safetyPct:33.333333,investmentPct:16.666667,cardTarget:5800,safetyTarget:24000,investmentTotal:0,startMonth:START_MONTH};
  let plan=JSON.parse(localStorage.getItem(PLAN_KEY)||'null')||defaultPlan;
  plan={...defaultPlan,...plan,startMonth:START_MONTH,cardPct:50,safetyPct:33.333333,investmentPct:16.666667,cardTarget:5800,safetyTarget:24000};
  function savePlan(){localStorage.setItem(PLAN_KEY,JSON.stringify(plan))}
  function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
  function m(v){const c=localStorage.getItem('currency')||'QAR';return c+' '+n(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
  function monthKey(d){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`}
  function currentMonth(){return localStorage.getItem('selectedMonth')||monthKey(new Date())}
  function getTransactions(){return JSON.parse(localStorage.getItem('finance')||'[]')}
  function getMonthlyStats(key){const all=getTransactions();const tx=key==='all'?all:all.filter(x=>monthKey(x.date||Date.now())===key);return tx.reduce((r,x)=>{if(x.type==='income')r.income+=n(x.amount);else r.expense+=n(x.amount);return r},{income:0,expense:0})}
  function isVacationMonth(key){return key==='2026-09'||key==='2026-10'}
  function getOutstandingCard(){
    const candidates=['creditCardOutstanding','cardOutstanding','creditCardBalance'];
    for(const k of candidates){const v=localStorage.getItem(k);if(v!==null&&Number.isFinite(Number(v)))return Math.max(0,Number(v))}
    return n(plan.cardTarget);
  }
  function safetySaved(){const goals=JSON.parse(localStorage.getItem('savingsGoals')||'[]');const g=goals.find(x=>{const name=String(x.name||'').toLowerCase();return name.includes('emergency')||name.includes('safety')});return g?n(g.saved):0}
  function ensurePanel(){
    const home=document.getElementById('home');if(!home||document.getElementById('moneyPlanPanel'))return;
    const panel=document.createElement('section');panel.id='moneyPlanPanel';panel.className='panel money-plan-panel';
    panel.innerHTML=`<div class="section-heading"><div><h3>🧭 Where Should My Balance Go?</h3><small id="mpSubtitle">Vacation: 17 Sep–31 Oct 2026 · Financial plan starts November 2026.</small></div></div><div class="money-plan-grid"><div class="money-plan-main"><div class="plan-total"><small id="mpAvailableLabel">November available balance</small><strong id="mpAvailable">QAR 0.00</strong></div><div class="allocation-row card"><div><strong>💳 Credit Card</strong><small id="mpCardPct">50%</small></div><strong id="mpCard">QAR 1,500.00</strong></div><div class="allocation-row emergency"><div><strong>🛡️ Safety Fund</strong><small id="mpSafetyPct">33.33%</small></div><strong id="mpSafety">QAR 1,000.00</strong></div><div class="allocation-row investment"><div><strong>📈 Investments</strong><small id="mpInvestmentPct">16.67%</small></div><strong id="mpInvestment">QAR 500.00</strong></div><div class="plan-note" id="mpAdvice"></div></div><div class="money-plan-side"><label>Credit-card balance<input id="mpCardTarget" type="number" inputmode="decimal"></label><label>Safety target<input id="mpSafetyTarget" type="number" inputmode="decimal"></label><label>Card %<input id="mpCardPctInput" type="number" min="0" max="100"></label><label>Safety %<input id="mpSafetyPctInput" type="number" min="0" max="100"></label><label>Investment %<input id="mpInvestmentPctInput" type="number" min="0" max="100"></label><button onclick="saveMoneyPlan()">Save Plan</button><small id="mpValidation" class="hint"></small></div></div><div class="plan-progress"><div><span>💳 Credit Card</span><strong id="mpCardProgress">QAR 5,800 outstanding</strong></div><div class="progress"><i id="mpCardBar" style="width:100%"></i></div><div><span>🛡️ Safety Fund</span><strong id="mpSafetyProgress">QAR 0 / QAR 24,000</strong></div><div class="progress"><i id="mpSafetyBar" style="width:0%"></i></div></div>`;
    const net=home.querySelector('.net-worth-card');net?home.insertBefore(panel,net):home.appendChild(panel);
  }
  window.saveMoneyPlan=function(){const c=n(document.getElementById('mpCardPctInput').value),s=n(document.getElementById('mpSafetyPctInput').value),i=n(document.getElementById('mpInvestmentPctInput').value),ct=n(document.getElementById('mpCardTarget').value),st=n(document.getElementById('mpSafetyTarget').value);if(Math.abs(c+s+i-100)>0.01){document.getElementById('mpValidation').textContent='Percentages must total 100%.';return}if(ct<0||st<=0){document.getElementById('mpValidation').textContent='Enter valid targets.';return}plan={...plan,cardPct:c,safetyPct:s,investmentPct:i,cardTarget:ct,safetyTarget:st,startMonth:START_MONTH};savePlan();document.getElementById('mpValidation').textContent='Saved ✓';renderPlan()};
  function renderPlan(){
    ensurePanel();const key=currentMonth();const vacation=isVacationMonth(key);const stats=getMonthlyStats(key);const available=vacation?0:Math.max(0,stats.income-stats.expense);const c=available*plan.cardPct/100,s=available*plan.safetyPct/100,i=available*plan.investmentPct/100;const card=getOutstandingCard(),saved=safetySaved(),target=n(plan.safetyTarget);const cp=plan.cardTarget?Math.max(0,Math.min(100,card/plan.cardTarget*100)):0;const sp=target?Math.min(100,saved/target*100):0;const set=(id,v)=>{const x=document.getElementById(id);if(x)x.textContent=v};
    set('mpAvailableLabel',vacation?'✈️ Vacation Mode — no financial-plan allocation':'Available for '+key+' plan');set('mpAvailable',m(available));set('mpCard',m(c));set('mpSafety',m(s));set('mpInvestment',m(i));set('mpCardPct',plan.cardPct+'%');set('mpSafetyPct',Number(plan.safetyPct).toFixed(2)+'%');set('mpInvestmentPct',Number(plan.investmentPct).toFixed(2)+'%');set('mpCardProgress',m(card)+' outstanding');set('mpSafetyProgress',m(saved)+' / '+m(target));const cb=document.getElementById('mpCardBar'),sb=document.getElementById('mpSafetyBar');if(cb)cb.style.width=cp+'%';if(sb)sb.style.width=sp+'%';
    const advice=document.getElementById('mpAdvice');if(advice){if(vacation)advice.textContent='✈️ Vacation Mode: 17 Sep–31 Oct 2026. Use the Kerala Vacation Tracker for India spending. Abdulla Finance will not allocate the balance during this period.';else if(stats.income===0)advice.textContent='Add your November salary transaction to calculate the actual surplus.';else if(available<=0)advice.textContent='No surplus this month. Avoid adding new credit-card spending.';else if(card>0)advice.textContent='Priority: pay down the credit card while keeping QAR 1,000/month going to your Safety Fund and QAR 500/month to investments.';else if(saved<target)advice.textContent='Credit card cleared. Redirect the QAR 1,500 card allocation to the Safety Fund until QAR 24,000 is reached.';else advice.textContent='Credit card and Safety Fund targets are complete. Redirect more of the monthly surplus toward investments.'}
    const ct=document.getElementById('mpCardTarget'),st=document.getElementById('mpSafetyTarget'),cpct=document.getElementById('mpCardPctInput'),spct=document.getElementById('mpSafetyPctInput'),ipct=document.getElementById('mpInvestmentPctInput');if(ct)ct.value=plan.cardTarget;if(st)st.value=plan.safetyTarget;if(cpct)cpct.value=plan.cardPct;if(spct)spct.value=plan.safetyPct;if(ipct)ipct.value=plan.investmentPct;
  }
  const oldRender=window.render;if(typeof oldRender==='function'){window.render=function(){oldRender();renderPlan()}}setTimeout(renderPlan,0);
})();