let recurringSalary=Number(localStorage.getItem('recurringSalary'))||7000;
const defaultMonthlyBudgets=[{category:'CBQ Loan',amount:988,kind:'fixed'},{category:'Home',amount:1500,kind:'fixed'},{category:'Rent',amount:400,kind:'flexible'},{category:'Food',amount:700,kind:'flexible'},{category:'Petrol',amount:400,kind:'flexible'}];
function saveRecurringSalary(){localStorage.setItem('recurringSalary',String(recurringSalary))}
function editRecurringSalary(){const v=Number(prompt('Monthly salary / recurring income',String(recurringSalary)));if(Number.isFinite(v)&&v>0){recurringSalary=v;saveRecurringSalary();renderSalary();if(typeof render==='function')render()}}
function ensureDefaultMonthlyBudgets(){let changed=false;if(!Array.isArray(budgetTemplate))budgetTemplate=[];defaultMonthlyBudgets.forEach(d=>{if(!budgetTemplate.some(x=>x.category===d.category)){budgetTemplate.push({id:'default-'+d.category,category:d.category,amount:d.amount,kind:d.kind});changed=true}});if(changed)saveTemplate()}
function applyRecurringForMonth(){if(typeof selectedMonth==='undefined'||selectedMonth==='all')return;ensureDefaultMonthlyBudgets();if(typeof budgets==='undefined')return;if(!budgets[selectedMonth])budgets[selectedMonth]={};let changed=false;budgetTemplate.forEach(x=>{if(budgets[selectedMonth][x.category]==null){budgets[selectedMonth][x.category]=x.amount;changed=true}});if(changed)saveBudgets()}
function getMonthlyPlannedExpense(){if(typeof budgets==='undefined'||typeof selectedMonth==='undefined'||selectedMonth==='all')return 0;return Object.values(budgets[selectedMonth]||{}).reduce((s,v)=>s+Number(v||0),0)}
function renderSalary(){const amount=document.getElementById('salaryAmount');if(amount)amount.textContent=money(recurringSalary);const old=document.getElementById('salaryPlanCard');if(old)old.remove();const home=document.getElementById('home');if(!home)return;const cards=document.createElement('section');cards.id='salaryPlanCard';cards.className='panel salary-plan-card';const planned=getMonthlyPlannedExpense();const remaining=recurringSalary-planned;cards.innerHTML=`<div class="section-heading"><div><h3>📅 Monthly Plan</h3><small>Automatically carried into each month. Edit any amount when it changes.</small></div></div><div class="plan-grid"><div><small>Monthly Salary</small><strong>${money(recurringSalary)}</strong></div><div><small>Planned Expenses</small><strong>${money(planned)}</strong></div><div><small>Planned Remaining</small><strong>${money(remaining)}</strong></div></div>`;const net=document.querySelector('.net-worth-card');if(net)home.insertBefore(cards,net);else home.appendChild(cards)}
const originalFinanceRender=typeof render==='function'?render:null;
if(originalFinanceRender){render=function(){applyRecurringForMonth();originalFinanceRender();renderSalary()}}
ensureDefaultMonthlyBudgets();applyRecurringForMonth();renderSalary();