let data=JSON.parse(localStorage.getItem('finance'))||[];let credit=JSON.parse(localStorage.getItem('credit'))||[];let savings=Number(localStorage.getItem('savings'))||0;let currency=localStorage.getItem('currency')||'QAR';let chart,reportChart;
function val(id){return document.getElementById(id).value}function money(v){return currency+' '+Number(v).toLocaleString()}function setCurrency(){currency=val('currency');localStorage.setItem('currency',currency);render()}function save(){localStorage.setItem('finance',JSON.stringify(data))}
function addTransaction(){let name=val('name'),amount=Number(val('amount')),type=val('type'),category=val('category');if(!name||!amount)return;data.push({id:Date.now(),name,amount,type,category,date:new Date().toISOString()});save();render()}
function addSaving(){let a=Number(val('saving'));if(a){savings+=a;localStorage.setItem('savings',savings);render()}}
function addCredit(){let person=val('person'),amount=Number(val('creditAmount')),type=val('creditType');if(!person||!amount)return;credit.push({id:Date.now(),person,amount,type,settled:0});localStorage.setItem('credit',JSON.stringify(credit));render()}
function settleCredit(id){let x=credit.find(i=>i.id===id),a=Number(prompt('Settlement amount'));if(x&&a){x.settled=Math.min(x.amount,x.settled+a);localStorage.setItem('credit',JSON.stringify(credit));render()}}
function editItem(id){let x=data.find(i=>i.id===id);if(x){x.name=prompt('Edit description',x.name)||x.name;x.amount=Number(prompt('Edit amount',x.amount))||x.amount;save();render()}}
function removeItem(id){data=data.filter(x=>x.id!==id);save();render()}
function exportData(){let b=new Blob([JSON.stringify({data,credit,savings,currency},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='abdulla-finance-backup.json';a.click()}
function drawCharts(i,e){let c=document.getElementById('chart');if(c&&typeof Chart!=='undefined'){if(chart)chart.destroy();chart=new Chart(c,{type:'doughnut',data:{labels:['Income','Expense'],datasets:[{data:[i,e]}]}})}let r=document.getElementById('reportChart');if(r&&typeof Chart!=='undefined'){if(reportChart)reportChart.destroy();reportChart=new Chart(r,{type:'bar',data:{labels:['Income','Expense','Savings'],datasets:[{data:[i,e,savings]}]}})}}
function render(){let i=0,e=0,cats={};data.forEach(x=>{x.type==='income'?i+=x.amount:e+=x.amount;if(x.type==='expense')cats[x.category]=(cats[x.category]||0)+x.amount});document.getElementById('income').textContent=money(i);document.getElementById('expense').textContent=money(e);document.getElementById('balance').textContent=money(i-e);let n=document.getElementById('netWorth');if(n)n.textContent=money(i-e+savings);let s=document.getElementById('savingTotal');if(s)s.textContent=money(savings);let a=document.getElementById('analytics');if(a)a.textContent=Object.entries(cats).map(x=>x[0]+': '+money(x[1])).join(' | ')||'No expenses yet';let list=document.getElementById('list');if(list)list.innerHTML=data.map(x=>`<li>${x.name} ${money(x.amount)} <button onclick="editItem(${x.id})">Edit</button><button onclick="removeItem(${x.id})">Delete</button></li>`).join('');let cl=document.getElementById('creditList');if(cl)cl.innerHTML=credit.map(x=>`<li>${x.person} ${x.type==='receive'?'🟢':'🔴'} ${money(x.amount-x.settled)} <button onclick="settleCredit(${x.id})">Settle</button></li>`).join('');drawCharts(i,e)}render();